name: Charales local
values:
  - key: baseUrl
    value: 'http://localhost:3000'
    enabled: true
    type: default
  - key: adminEmail
    value: admin@example.com
    enabled: true
    type: default
  - key: disabledEmail
    value: baja@example.com
    enabled: true
    type: default
  - key: password
    value: demo1234
    enabled: true
    type: default
