import { DateTime, Id, ISODate } from './common';

export type PlayerStatus = 'ACTIVO' | 'BAJA_TEMPORAL' | 'BAJA_DEFINITIVA';
export type Sex = 'F' | 'M' | 'OTRO' | 'NO_ESPECIFICADO';

/** jugadores */
export interface Player {
  id: Id;
  /** Internal identifier (HU-008), unique, generated by the system: 'J-0001'. */
  identifier: string;
  firstName: string;
  lastName1: string;
  lastName2: string | null;
  birthDate: ISODate;
  sex: Sex;
  phone: string | null;
  email: string | null;
  address: string | null;
  status: PlayerStatus;
  createdAt: DateTime;
  updatedAt: DateTime;
}

/** historial_estatus */
export interface PlayerStatusChange {
  id: Id;
  playerId: Id;
  previousStatus: PlayerStatus | null;
  newStatus: PlayerStatus;
  reason: string | null;
  changedBy: Id | null;
  changedAt: DateTime;
}

/** tutores. Exists with or without an account; userId set = portal access. Contact data, not login. */
export interface Tutor {
  id: Id;
  userId: Id | null;
  firstName: string;
  lastName1: string;
  lastName2: string | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  createdAt: DateTime;
  updatedAt: DateTime;
}

/** tutor_jugador. The relationship (parentesco) belongs to the pair; at most one primary contact per player. */
export interface TutorPlayer {
  tutorId: Id;
  playerId: Id;
  relationship: string;
  isPrimary: boolean;
  createdAt: DateTime;
}

/** entrenadores. `active` is the sporting status, independent from the account's usuarios.activo. */
export interface Coach {
  id: Id;
  userId: Id | null;
  firstName: string;
  lastName1: string;
  lastName2: string | null;
  phone: string | null;
  email: string | null;
  active: boolean;
  createdAt: DateTime;
  updatedAt: DateTime;
}

export function fullName(p: {
  firstName: string;
  lastName1: string;
  lastName2: string | null;
}): string {
  return [p.firstName, p.lastName1, p.lastName2].filter(Boolean).join(' ');
}
